let data = {
    2000: {
        "alpine activity": 0,
        "aquatic play": 6,
        "cars & track rides": 11,
        "challenge activity": 0,
        "coaster": 25,
        "float attraction": 4,
        "go-kart": 17,
        "inflatable": 2,
        "other attraction": 12,
        "pendulum": 6,
        "play equipment": 5,
        "spinning": 21,
        "trampoline": 0,
        "vertical drop": 1,
        "water ride": 12,
        "water slide": 28,
        "wave device": 0

    },

    2001: {
        "alpine activity": 1,
        "aquatic play": 3,
        "cars & track rides": 24,
        "challenge activity": 2,
        "coaster": 35,
        "float attraction": 2,
        "go-kart": 27,
        "inflatable": 1,
        "other attraction": 8,
        "pendulum": 1,
        "play equipment": 5,
        "spinning": 27,
        "trampoline": 0,
        "vertical drop": 5,
        "water ride": 12,
        "water slide": 38,
        "wave device": 3
    },

    2002: {
        "alpine activity": 0,
        "aquatic play": 2,
        "cars & track rides": 11,
        "challenge activity": 0,
        "coaster": 29,
        "float attraction": 2,
        "go-kart": 13,
        "inflatable": 2,
        "other attraction": 1,
        "pendulum": 2,
        "play equipment": 7,
        "spinning": 30,
        "trampoline": 1,
        "vertical drop": 2,
        "water ride": 22,
        "water slide": 34,
        "wave device": 2
    },

    2003: {
        "alpine activity": 0,
        "aquatic play": 6,
        "cars & track rides": 5,
        "challenge activity": 1,
        "coaster": 14,
        "float attraction": 2,
        "go-kart": 12,
        "inflatable": 0,
        "other attraction": 10,
        "pendulum": 3,
        "play equipment": 1,
        "spinning": 7,
        "trampoline": 1,
        "vertical drop": 2,
        "water ride": 114,
        "water slide": 28,
        "wave device": 2
    },

    2004: {
        "alpine activity": 2,
        "aquatic play": 3,
        "cars & track rides": 6,
        "challenge activity": 0,
        "coaster": 35,
        "float attraction": 5,
        "go-kart": 10,
        "inflatable": 0,
        "other attraction": 2,
        "pendulum": 2,
        "play equipment": 2,
        "spinning": 18,
        "trampoline": 1,
        "vertical drop": 1,
        "water ride": 5,
        "water slide": 26,
        "wave device": 0
    },

    2005: {
        "alpine activity": 0,
        "aquatic play": 5,
        "cars & track rides": 10,
        "challenge activity": 1,
        "coaster": 20,
        "float attraction": 2,
        "go-kart": 6,
        "inflatable": 2,
        "other attraction": 5,
        "pendulum": 2,
        "play equipment": 0,
        "spinning": 16,
        "trampoline": 0,
        "vertical drop": 0,
        "water ride": 10,
        "water slide": 22,
        "wave device": 3
    },

    2006: {
        "alpine activity": 0,
        "aquatic play": 2,
        "cars & track rides": 5,
        "challenge activity": 2,
        "coaster": 16,
        "float attraction": 2,
        "go-kart": 11,
        "inflatable": 3,
        "other attraction": 1,
        "pendulum": 2,
        "play equipment": 1,
        "spinning": 16,
        "trampoline": 0,
        "vertical drop": 0,
        "water ride": 6,
        "water slide": 14,
        "wave device": 3
    },

    2007: {
        "alpine activity": 0,
        "aquatic play": 3,
        "cars & track rides": 4,
        "challenge activity": 0,
        "coaster": 8,
        "float attraction": 0,
        "go-kart": 6,
        "inflatable": 4,
        "other attraction": 6,
        "pendulum": 3,
        "play equipment": 0,
        "spinning": 14,
        "trampoline": 0,
        "vertical drop": 0,
        "water ride": 7,
        "water slide": 22,
        "wave device": 2
    },

    2008: {
        "alpine activity": 0,
        "aquatic play": 1,
        "cars & track rides": 2,
        "challenge activity": 0,
        "coaster": 0,
        "float attraction": 0,
        "go-kart": 0,
        "inflatable": 0,
        "other attraction": 1,
        "pendulum": 0,
        "play equipment": 0,
        "spinning": 4,
        "trampoline": 0,
        "vertical drop": 1,
        "water ride": 1,
        "water slide": 1,
        "wave device": 1
    }




};
